# documentation at http://goreleaser.com

dist: ./_dist

before:
  hooks:
    - go mod tidy

builds:
  - id: ""

    env:
      - CGO_ENABLED=0

    main: .

    ldflags:
      - -s -w
        -X main.BuildVersion={{.Version}}
        -X main.BuildGitBranch={{.Env.BuildGitBranch}}
        -X main.BuildGitRev={{.Env.BuildGitRev}}
        -X main.BuildGitCommit={{.Env.BuildGitCommit}}
        -X main.BuildDate={{.Date}}
        -X main.BuildBy=goreleaser

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64

archives:

  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64

    name_template: "{{.Binary}}-{{.Os}}-{{.Arch}}-{{.Version}}"

    format: tar.gz

    format_overrides:
      - goos: windows
        format: zip

    files:
      - "LICENSE*"
      - "README*"
      - "CHANGELOG*"

checksum:
  name_template: 'checksums.txt'

signs:
  - signature: "${artifact}.asc"

    cmd: gpg

    args: ["--output", "${signature}", "--clear-sign", "${artifact}"]

    artifacts: all

snapshot:
  name_template: "{{.Tag}}-SNAPSHOT"

changelog:
  skip: true
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^typo:'

dockers:
  - dockerfile: ./Dockerfile

    goos: linux

    goarch: amd64

    image_templates:
      - "quay.io/yingzhuo/docktool:latest"
      - "quay.io/yingzhuo/docktool:{{.Tag}}"
      - "yingzhuo/docktool:latest"
      - "yingzhuo/docktool:{{.Tag}}"

    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"

    skip_push: true
